#!/bin/bash
if [ $1 == 'install' ]
then
  mv xx /usr/local/bin/xx
  chmod 775 /usr/local/bin/xx
  wget https://raw.githubusercontent.com/iuv/xx/master/xx.py -O /usr/local/bin/xx.py
elif [ $1 == 'update' ]
then
  wget https://raw.githubusercontent.com/iuv/xx/master/xx -O /usr/local/bin/xx
  chmod 775 /usr/local/bin/xx
  wget https://raw.githubusercontent.com/iuv/xx/master/xx.py -O /usr/local/bin/xx.py
else
python /usr/local/bin/xx.py $1 $2 $3 $4 $5 $6
fi
